---
- name: Installing and testing cmake
  hosts: all
  tasks:
    - name: Install cmake
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
    - name: Testing 'cmake --version'
      ansible.builtin.command: /usr/local/bin/cmake --version
      changed_when: false
      register: cmake_test_output
    - name: Output of 'cmake --version'
      ansible.builtin.debug:
        msg: '{{ cmake_test_output.stdout }}'
